Update README.md
unofficial-unifi/unifi-pfsense pull request #266
Opened 2021-12-01 03:42 UTC by tong2x

Compatibility upgrade to MONGODB 4.2
for those having crashes after upgrading to latest Unifi Controller with MongoDB 4.0 and 4.2

2021-12-01 08:42 UTC, shortbloke requested changes
Some suggested changes to the text.

2021-12-01 08:42 UTC, shortbloke commented on README.md
> +The follow is the work around for upgrading MongoDB 3.6 to MonggoDB 4.2. This is to resolve conflict and crashes in Unifi Controller relating to MongoDB:
Follow should be following and workaround is all one word, I believe.
Suggested change: "The following is a workaround for upgrading MongoDB 3.6 to MonggoDB 4.2 to resolve conflict and crashes in Unifi Controller related to MongoDB versions."

2021-12-01 08:42 UTC, shortbloke commented on README.md
> +At this point you have a mongodb that was upgraded from 3.6 to 4.0, then the database files were upgraded to 4.0 compatible, then upgrading to mongodb 4.2. allows you to see that it indeed works with
Suggested text: 
"At this point you have a mongodb that was upgraded from 3.6 to 4.0, the database itself has been upgraded to be 4.0 compatible, finally mongodb 4.2 has been installed. Any database repairs will be handled automatically by the installation script."

2022-03-01 03:35 UTC, slmingol approved these changes

2022-07-07 05:45 UTC, merged